name: "Javalent Discord Embed"
description: "Discord Embed PR Release Notes"
author: "Jeremy Valentine"
inputs:
    webhook-urls:
        description: Array of webhook URLs to post to.
        default: "[]"
        required: true
    repo:
        description: Override repo being ran
    name:
        description: Name to use for release notification
    beta:
        description: This release is a beta release.
runs:
    using: "node20"
    main: "../dist/discord-embed.js"
