# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "greet"
    greet:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            # Runs a single command using the runners shell
            - name: Send greeting
              run: echo "Hello ${{ github.event.inputs.name }}"
            - name: Read VERSION file
              id: contents
              run: echo "::set-output name=contents::$(cat README.md)"
            - name: Discord Webhook Action
              uses: tsickert/discord-webhook@v5.3.0
              with:
                  webhook-url: https://discord.com/api/webhooks/1087082443133161533/lFC1g_L1NqWfsYQub3wE4FQY-HTyESZAAlVz8fXFbT9LVPxCX4AbC8fLtF1l5HBo1g5L
                  raw-data: raw.json
